import {
	openModalCreationNews,
	openModalEditNews,
	newsListRequested,
	newsListLoaded,
	newsListError,
	fetchNewsList,
	showAllNews,
	newsImageRequested,
	newsImagePosted,
	newsImageError,
	newsDataRequested,
	newsDataPosted,
	newsDataError,
	putNewsRequested,
	putNewsSuccess,
	putNewsError,
	newsDeleteRequested,
	newsDeleted,
	newsDeleteError,
	addIdNewsDeleted
} from './news';

export {
	openModalCreationNews,
	openModalEditNews,
	newsListRequested,
	newsListLoaded,
	newsListError,
	fetchNewsList,
	showAllNews,
	newsImageRequested,
	newsImagePosted,
	newsImageError,
	newsDataRequested,
	newsDataPosted,
	newsDataError,
	putNewsRequested,
	putNewsSuccess,
	putNewsError,
	newsDeleteRequested,
	newsDeleted,
	newsDeleteError,
	addIdNewsDeleted
};